### PR TITLE
Initialize consumer and listen to avscan events

### PR DESCRIPTION
**Pull request by himaniraghav3**
This pull request aims to initialise a consumer in app.js which will listen to all events in the AVSCAN_TOPIC.

### CODE REVIEW

**Review by ThomasKranitsas — CHANGES_REQUESTED** [review]
@himaniraghav3 please find my review comments below:

1. The param `downloadedFile` of `processScan` is null by default and then you check its value but you never actually pass anything into that parameter. Why are we defining this as a parameter then?
2. The `maxRetries` is declared but never used in the `processScan` method parameters.
3. You are reading from `config` but that's never defined/imported. This will result in an error.
4. In `helper.js` you're using the Auth0 configs but those are commented out in `./config/default.js`. This will result in an error.
5. You are mixing `async/await` syntax with `function generators (*/yield)`. You should use `await` instead of `yield` and use `async` functions instead of function generators `*`.
6. `helper.postToBusAPI(message);` - the `postToBusAPI` is an async function, you should use `await`
7. You're mixing single quotes with double quotes. Please use a consistent coding format otherwise the code will end up hard to maintain.
8. `REVIEW_SCORECARDID` is never defined or imported. This will result in an error
9. `AV_SCAN` is never defined or imported. This will result in an error

**Comment by himaniraghav3** [comment]
> @himaniraghav3 please find my review comments below:
> 
> 1. The param `downloadedFile` of `processScan` is null by default and then you check its value but you never actually pass anything into that parameter. Why are we defining this as a parameter then?
> 2. The `maxRetries` is declared but never used in the `processScan` method parameters.
> 3. You are reading from `config` but that's never defined/imported. This will result in an error.
> 4. In `helper.js` you're using the Auth0 configs but those are commented out in `./config/default.js`. This will result in an error.
> 5. You are mixing `async/await` syntax with `function generators (*/yield)`. You should use `await` instead of `yield` and use `async` functions instead of function generators `*`.
> 6. `helper.postToBusAPI(message);` - the `postToBusAPI` is an async function, you should use `await`
> 7. You're mixing single quotes with double quotes. Please use a consistent coding format otherwise the code will end up hard to maintain.
> 8. `REVIEW_SCORECARDID` is never defined or imported. This will result in an error
> 9. `AV_SCAN` is never defined or imported. This will result in an error

1. By making the downloadedFile parameter optional, the processScan function can be reused in different parts of the codebase where the file might be already downloaded or fetched before the scanning process.
2. Removing `maxTries` as it's not needed.
3. Done
4. Needs discussion
5. Done
6. Done
7. Done - using double quotes only
8. Needs discussion
9. Done

**Review by ThomasKranitsas — CHANGES_REQUESTED** [review]
3. is not fixed correclty. We're using the https://www.npmjs.com/package/config package. You should require `config` as `const config = require('config')` instead of requiring the `default.js` file directly. The package will then load the configurations as expected.
4. Can you elaborate on this? If the configs for Auth0 are required in `helper.js` they need to be available in `config/default.js`
5. This is still not done. In `helper.js` you still have function generators
6. Ok
7. Ok, though, it's a best practice to use single quotes but it's not a big deal.
8. Let's discuss this. What's the need here?
9. There's a typo. You have defined it as `AV_Scan` and you're then reading it as `AV_SCAN`. This will throw an error.

**Review by ThomasKranitsas — CHANGES_REQUESTED** [review]
In your `helper.js`, you changed `function *` to `async function` but you're still using `yield`. You should use `await` instead

**Review by ThomasKranitsas — APPROVED** [review]

**Pull request merged**
